import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "installation",
        {
          type: "category",
          label: "Configuration",
          collapsed: false,
          items: [
            "configuration",
            "configuration/plex",
            "configuration/jellyfin",
            "configuration/trakt",
            "configuration/tvtime",
          ],
        },
      ],
    },
    "how-it-works",
    "architecture",
    {
      type: "category",
      label: "REST API",
      link: {
        type: "generated-index",
        title: "REST API",
        description:
          "Generated from `packages/backend/openapi.yaml`. Regenerate with `pnpm gen-api-docs` in `website/` when the spec changes.",
        slug: "/category/rest-api",
      },
      items: [{ type: "autogenerated", dirName: "api" }],
    },
    "troubleshooting",
  ],
};

export default sidebars;
