---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Test docs build

on:
  pull_request:
    branches: [main]
    paths:
      - "website/**"
      - "docs/**"
      - "packages/backend/openapi.yaml"
      - ".github/workflows/test-docs.yml"

jobs:
  test-deploy:
    name: Test docs build
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320  # v4.4.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build website
        env:
          BASE_URL: "/scroblarr/"
        run: pnpm build:docs
